# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_tr_mat <- function(n, Theta, genotypes, node_labels) {
    .Call(`_TreeMHN_build_tr_mat`, n, Theta, genotypes, node_labels)
}

compute_obs_ll <- function(tr_mat, lambda_s) {
    .Call(`_TreeMHN_compute_obs_ll`, tr_mat, lambda_s)
}

compute_prob_ij <- function(tr_mat, lambda_s, i, j) {
    .Call(`_TreeMHN_compute_prob_ij`, tr_mat, lambda_s, i, j)
}

tree_E_step <- function(Theta, n, lambda_s, nodes, children, in_tree, genotypes, node_labels) {
    .Call(`_TreeMHN_tree_E_step`, Theta, n, lambda_s, nodes, children, in_tree, genotypes, node_labels)
}

tree_importance_sampling <- function(Theta, nodes, children, in_tree, n, M, lambda_s) {
    .Call(`_TreeMHN_tree_importance_sampling`, Theta, nodes, children, in_tree, n, M, lambda_s)
}

full_MHN_objective_ <- function(Theta, trees, gamma, n, N, lambda_s, to_mask, weights) {
    .Call(`_TreeMHN_full_MHN_objective_`, Theta, trees, gamma, n, N, lambda_s, to_mask, weights)
}

full_MHN_grad_ <- function(Theta, trees, gamma, n, N, lambda_s, to_mask, weights) {
    .Call(`_TreeMHN_full_MHN_grad_`, Theta, trees, gamma, n, N, lambda_s, to_mask, weights)
}

obs_MHN_objective_ <- function(Theta, n, N, lambda_s, trees, gamma, obj_grad_help, to_mask, weights) {
    .Call(`_TreeMHN_obs_MHN_objective_`, Theta, n, N, lambda_s, trees, gamma, obj_grad_help, to_mask, weights)
}

obs_MHN_grad_ <- function(Theta, n, N, lambda_s, trees, gamma, obj_grad_help, to_mask, weights) {
    .Call(`_TreeMHN_obs_MHN_grad_`, Theta, n, N, lambda_s, trees, gamma, obj_grad_help, to_mask, weights)
}

get_augmented_trees <- function(n, trees) {
    .Call(`_TreeMHN_get_augmented_trees`, n, trees)
}

parse_trees <- function(path) {
    .Call(`_TreeMHN_parse_trees`, path)
}

rtexp <- function(lambda, lbound, ubound) {
    .Call(`_TreeMHN_rtexp`, lambda, lbound, ubound)
}

get_lambda <- function(node, Theta) {
    .Call(`_TreeMHN_get_lambda`, node, Theta)
}

