# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_tr_mat <- function(n, Theta, genotypes, node_labels, lambda_s) {
    .Call(`_TreeMHN_build_tr_mat`, n, Theta, genotypes, node_labels, lambda_s)
}

compute_obs_ll <- function(tr_mat, lambda_s) {
    .Call(`_TreeMHN_compute_obs_ll`, tr_mat, lambda_s)
}

update_timed_trees <- function(n, N, timed_trees, Theta, lambda_s, M, log_prob_vec, comp_geno_vec, node_labels_vec, nr_exact) {
    invisible(.Call(`_TreeMHN_update_timed_trees`, n, N, timed_trees, Theta, lambda_s, M, log_prob_vec, comp_geno_vec, node_labels_vec, nr_exact))
}

full_MHN_objective <- function(Theta, trees, gamma, n, N, lambda_s, to_mask, weights, N_patients, smallest_tree_size = 1) {
    .Call(`_TreeMHN_full_MHN_objective`, Theta, trees, gamma, n, N, lambda_s, to_mask, weights, N_patients, smallest_tree_size)
}

full_MHN_grad <- function(Theta, trees, gamma, n, N, lambda_s, to_mask, weights, N_patients, smallest_tree_size = 1) {
    .Call(`_TreeMHN_full_MHN_grad`, Theta, trees, gamma, n, N, lambda_s, to_mask, weights, N_patients, smallest_tree_size)
}

obs_MHN_objective <- function(Theta, n, N, lambda_s, trees, gamma, tr_mat_vec, log_prob_vec, comp_geno_vec, node_labels_vec, to_mask, weights, N_patients, smallest_tree_size = 1) {
    .Call(`_TreeMHN_obs_MHN_objective`, Theta, n, N, lambda_s, trees, gamma, tr_mat_vec, log_prob_vec, comp_geno_vec, node_labels_vec, to_mask, weights, N_patients, smallest_tree_size)
}

obs_MHN_grad <- function(Theta, n, N, lambda_s, trees, gamma, tr_mat_vec, log_prob_vec, comp_geno_vec, node_labels_vec, to_mask, weights, N_patients, smallest_tree_size = 1) {
    .Call(`_TreeMHN_obs_MHN_grad`, Theta, n, N, lambda_s, trees, gamma, tr_mat_vec, log_prob_vec, comp_geno_vec, node_labels_vec, to_mask, weights, N_patients, smallest_tree_size)
}

get_augmented_trees <- function(n, trees) {
    .Call(`_TreeMHN_get_augmented_trees`, n, trees)
}

get_lambda <- function(node, Theta) {
    .Call(`_TreeMHN_get_lambda`, node, Theta)
}

